import Head from 'next/head'
import Image from 'next/image'
import AboutMe from '../components/AboutMe'
import LandingPage from '../components/LandingPage'
import { ParallaxProvider } from 'react-scroll-parallax';
import Skills from '../components/Skills';

export default function Home() {
  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <ParallaxProvider>
       <LandingPage/>
       <AboutMe/>
       <Skills/>
       </ParallaxProvider>
      </main>

    </section>
   
  )
}
