import Head from 'next/head'
import AboutMe from '../components/AboutMe'
import LandingPage from '../components/LandingPage'
import { ParallaxProvider } from 'react-scroll-parallax';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Statistics from '../components/Statistics';
import Timeline from '../components/Timeline';
import Footer from '../components/Footer';

export default function Home() {


  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <ParallaxProvider>
       <LandingPage/>
       <AboutMe/>
       <Skills/>
       <Projects />
       <Statistics/>
       <Timeline/>
       </ParallaxProvider>
       <Footer />
      </main>

    </section>
   
  )
}
